version: "3.8"

services:
  backend:
    build: .
    container_name: portfolio-backend
    restart: always
    environment:
      - PORT=9060
      - SERVER_URL=http://141.11.182.146:9060
      - MONGO_URI=mongodb://mongo:27017/portfolio
      - TELEGRAM_BOT_TOKEN=7396199760:AAFVE3sxUtr0sHwvptYCBQ8_qPstElCcdz4
      - ADMIN_CHAT_ID=your_admin_chat_id_here
      - TELEGRAM_PROXY_URL=https://telegram.isatispooya.com
      - CORS_ORIGINS=http://141.11.182.146:8080,http://localhost:3000
    ports:
      - "9060:9060"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=portfolio
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
